// Prompts for the free-typing bonus round
const freeTexts = [
  "Jake was late to the meeting, but the elevator was taking too long...",
  "Sarah missed the bus, so she decided to...",
  "Tom was hungry, but there was nothing in the fridge...",
  "Lisa arrived at the station just as the train...",
  "Mark forgot his umbrella, and then it suddenly...",
  "Emily was tired after work, so she decided to...",
  "Daniel opened the door, but nobody was...",
  "Anna was looking for her keys when she suddenly...",
  "Peter wanted to call his friend, but his phone...",
  "John left the house early because he needed to...",
  "Maria was cooking dinner when the lights...",
  "David couldn't find his wallet, so he started...",
  "Emma was walking home when she noticed...",
  "Michael had an important meeting, but he had forgotten to...",
  "Sophie was waiting for the bus when someone...",
  "James heard a strange noise coming from...",
  "Laura wanted to buy a new laptop, but...",
  "Kevin arrived at the restaurant, but his friends...",
  "Rachel was about to leave when her boss...",
  "Andrew went to the supermarket because he needed to...",
  "Daniel was watching TV when someone knocked...",
  "Julia didn't have enough time to make breakfast, so...",
  "Chris was driving to work when his car...",
  "Megan looked outside and saw that it...",
  "Robert wanted to go for a walk, but it started...",
  "Alice was cleaning her room when she found...",
  "Steven couldn't sleep because his neighbors...",
  "Natalie got to the airport early, but her flight...",
  "Brian was reading a book when he realized...",
  "Kate was getting ready for bed when she heard...",
  "George forgot about the appointment, so he had to...",
  "Olivia was on her way home when she received...",
  "Frank opened his computer, but it wouldn't...",
  "Helen went into the kitchen to make some coffee, but...",
  "William was running late, so he decided to...",
  "Jessica was talking to her friend when the phone...",
  "Peter wanted to take a taxi, but there weren't any...",
  "Amy was waiting outside the store when she noticed...",
  "Richard had planned to spend the weekend at home, but...",
  "Susan was about to start cooking when she realized she had forgotten to...",
  "Emma was trying to do her homework, but the internet suddenly...",
  "Ryan missed the train, so he decided to...",
  "Ben was in the middle of cooking, but the smoke alarm...",
  "Zoe arrived at the gym and discovered the doors...",
  "Sam forgot his wallet, and then he realized...",
  "Lily was about to grab her coffee when the barista...",
  "Tyler was walking to the bus stop when he heard...",
  "Mia was setting the table when she noticed...",
  "Noah wanted to surprise his girlfriend, but her phone...",
  "Ava was walking in the park when she suddenly...",
  "Lucas was reading the newspaper when he realized...",
  "Hannah was trying to fix the sink, but the water...",
  "Ethan was about to lock the door when he heard...",
  "Grace was cooking tacos when the oven suddenly...",
  "Owen forgot his glasses, so he started...",
  "Madison was getting ready for class when her alarm...",
  "Liam was waiting for the elevator when someone...",
  "Chloe was cleaning her desk when she found...",
  "Jack wanted to send a text, but his phone...",
  "Ella was about to turn on the news when she noticed...",
  "I was trying to finish my report when the Wi-Fi suddenly died...",
  "I missed the bus again, so I decided to...",
  "I was in the middle of lunch when the smoke alarm went off...",
  "I arrived at the gym and the doors were locked...",
  "I forgot my wallet, so I had to run back and...",
  "I was about to grab my coffee when the barista spilled...",
  "I was walking to the stop when I heard my name...",
  "I was setting the table when my cat jumped on...",
  "I wanted to surprise my friend but her phone was off...",
  "I was walking through the park when I saw someone...",
  "I was reading the news when I realized I'd missed...",
  "I was trying to fix the faucet when the water turned...",
  "I was about to lock the door when I heard a noise...",
  "I was cooking tacos when the oven beeped...",
  "I forgot my glasses so I had to go back for...",
  "I was getting ready for class when my alarm started...",
  "I was waiting for the elevator when the doors opened...",
  "I was cleaning my desk when I found an old note...",
  "I was about to send a text when my phone started...",
  "I was turning on the news when I saw something...",
];
